### ISSUE TITLE
[Enhancement] Option to disable right click/scroll on menu

### ISSUE THREAD

**Issue by Batresh** [phillbush/xmenu#17]
Small nitpick issue... Sometimes my mouse/trackpad doubleclicks whenever i right click, opening the menu and then opening the first option. Scrolling by mistake while on menu also executes.
Would be a cool feature to have the option to disable mouse buttons/scroll

**Comment by phillbush** [comment]
The last commit adds a `-r` option that disables the right menu button.  
Triggering menu items on scrolling was disabled, it was a bug.

Thanks for reporting the issue!
