### ISSUE TITLE
Xresources font choice format?

### ISSUE THREAD

**Issue by GideonWolfe** [phillbush/xmenu#31]
So I just set up `xmenu` on my new laptop and am using the `AUR` package and the `.Xresources` theming for the first time (also added it for pmenu) and it works great!!

The only issue is that previously I specified a font inside `config.h` (FontAwesome) that I was using for icon characters/symbols that wouldn't look out of place. 

![image](https://user-images.githubusercontent.com/32942052/145724112-be9f193f-55ea-4fa9-9884-2d6f8a518534.png)

Since switching to this new configuration method, my FontAwesome icons show up as absurdly small

![image](https://user-images.githubusercontent.com/32942052/145724194-89c62972-5064-4a33-ba32-934256c8737b.png)

This is how I was configuring my fonts in `config.h`

```c
  .font = "HackNerdFont:size=9,FontAwesome:size=9",
```

And this is how I am configuring them in my `.Xresources`

```
xmenu.font:                  xft:Hack Nerd Font Mono:size=8:antialias=true,xft:FontAwesome:style=Regular:pixelsize=12
```

Any ideas why I'm getting a super small size for these characters? I've tried ajusting `pixelsize`, `size`, I'm not sure how to make them bigger.

**Comment by phillbush** [comment]
The `.Xresources` value does not have a `xft:` prefixed to each font.  
(But it should? since the same resource for `xterm(1)` needs the `xft:` prefix?).  
In fact, both the resource and the config.h values have the same syntax, so just copy the string from config.h into the Xresources file.

**Comment by GideonWolfe** [comment]
Fantastic, copying the string worked just fine :) Thanks again!
