### ISSUE TITLE
Create search item

### ISSUE THREAD

**Issue by SingularisArt** [phillbush/xmenu#36]
Just like we have any linux menu, they have a search menu. How can I add this to xmenu? This is what I've currently got.
![fff](https://user-images.githubusercontent.com/57925294/208586382-95f21bee-4250-485a-bbec-1c3bfdf7769d.png)

Here's what I would like to have. When I hover over the Search item on the xmenu selection list, I would like to be able to type, and it'll autofill, like the following.
![fff](https://user-images.githubusercontent.com/57925294/208586517-3f9d4931-ba6c-40f5-997d-94efc597853c.png)
Then, it'll start to filter out all the items.
How can I achieve this?

**Comment by phillbush** [comment]
Hi, xmenu does not have such text input field feature, nor it can search for items down the menu hierarchy.  
Drawing text fields is a complex task, especially when handling input methods and composed strings, that I prefer to be handled by a separate application.  
You can use, however, [dmenu](https://tools.suckless.org/dmenu/) for searching for items.   
You can make your workflow use xmenu for a mouse-based selection of items and dmenu for a keyboard-driven selection of items.

If you want to include such feature by yourself, you can fork xmenu and use dmenu's code to add its feature into xmenu.
