### ISSUE TITLE
Add option to place `xmenu` in the center of the screen

### ISSUE THREAD

**Issue by abrendtro** [phillbush/xmenu#39]
I have `xmenu` bound to a keyboard shortcut, so it always appears next to the cursor. I can add `-p 0x0:0` to place it in the top-left corner, but I'd rather see it directly in front of me. Could there be an option (`-c`, maybe) to place each popup in the monitor's center?

**Comment by phillbush** [comment]
Hi,
Opening `xmenu` at the center of the monitor can be done with some shell scripting and parsing the output of `xrandr`.
