### ISSUE TITLE
Background colour not changing on bspwm

### ISSUE THREAD

**Issue by Dinglesworth** [phillbush/xmenu#4]
Love the menu and it works really well with my workflow the only issue that I'm having though is that the background of the menu does not change when changing the setting in the config.h file all of the other colours work however background does not.

**Comment by phillbush** [comment]
XMenu respects the colors on `.XResources` over the colors set on `config.h`. You probably have a line like this in your `.XResources` file (or other file read by `xrdb(1)`):

```
*background: #XXXXXX
```

If the background color of XMenu is the same as the background color of your terminal, this is probably the case.

Try to set the XMenu background in your `.XResources` as the following:

```
xmenu.background: #XXXXX
```

And them run `xrdb` on that file.

You can also set other XMenu colors and properties via `.XResources`.
