### ISSUE TITLE
Hide, but don't close `xmenu` after selecting an option

### ISSUE THREAD

**Issue by abrendtro** [phillbush/xmenu#40]
Re-running `xmenu` is a bit redundant. Ideally, I would redirect its output to `sh` and set a hotkey to focus it. That way, `xmenu` would appear instantly.

**Comment by phillbush** [comment]
Hi,
There's the option `-x` that does what you need:

```
xmenu -x Mod4-3 <<EOF &
```

Then pressing Mod-4 (Super/Win key) with the third mouse button (right button) opens the same xmenu instance without needing to reopen it.

That needs to be run in the background.
