### ISSUE TITLE
Reduce the width

### ISSUE THREAD

**Issue by Ved-un** [phillbush/xmenu#47]
Best wishes for good health!    

In the drop-down menu (with an arrow) menu is correct    

![flameshot_162_1](https://github.com/phillbush/xmenu/assets/48730277/3d14c694-3422-4f0a-840d-42bec37be307)

But in the regular menu at the end, for some reason remains this gap (where the arrow)    

![flameshot_162](https://github.com/phillbush/xmenu/assets/48730277/36cd732f-0ca7-4b18-a5e9-3a081f4bf6c2)

**Comment by phillbush** [comment]
Hi, thanks for reporting the issue. It should be fixed now.

**Comment by Ved-un** [comment]
Thanks for the correction

It's a little wider than it was.    

![flameshot_162_2](https://github.com/phillbush/xmenu/assets/48730277/334acd1d-f3e8-4394-90e5-42a4f463da61)

But I fixed line 902 from 2 to 1.5

`itemwidth = item->textw + config.triangle_width + config.horzpadding * 1.5;`

and now everything is fine.    

![flameshot_162_3](https://github.com/phillbush/xmenu/assets/48730277/d9e0752c-e4f3-4a13-861f-df9b20e9e3d2)

**Comment by phillbush** [comment]
Oh, sorry, I forgot to remove the sum of  `config.triangle_width` on that line.
It should be fixed now.

**Comment by Ved-un** [comment]
Thank you, it's OK now.
