### ISSUE TITLE
Point to svg file for icon

### ISSUE THREAD

**Issue by GideonWolfe** [phillbush/xmenu#5]
Currently I am trying to use dynamically generated icons to match my theme. These are all SVGs, and xmenu says 

` xmenu: cannot load icon /home/gideon/.icons/oomox-xresources-reverse-flat/apps/scalable/browser.svg`

**Comment by phillbush** [comment]
Xmenu does not support svg images, you need to convert them to png using imagemagick or inkscape, and cache them on `~/.cache/`, for example.

**Comment by GideonWolfe** [comment]
Ah ok. How would I go about adding a fallback font? I am trying to render FontAwesome characters instead of icons for some items. Ideally I would like to use the `Hack` font and then `FontAwesome` so the icons will render.

Currently they are just boxes.

**Comment by phillbush** [comment]
Currently xmenu does not support fallback fonts, but I am working on that for the next release.  
If you want support for fallback fonts, you can use [jgmenu](https://github.com/johanmalm/jgmenu), a more sophisticated menu application that I think it supports multiple fonts.

**Comment by GideonWolfe** [comment]
Ok, thanks for the info. I have one final question. I am trying to make line breaks / horizontal rules within nested lists, but when I add an empty line within the nested list in my script, I get the `reached NULL element` error.

Is this expected behavior?

**Comment by phillbush** [comment]
Hmm, can I see the input you sent to xmenu?

**Comment by GideonWolfe** [comment]
Ah that's it, I needed the correct number of leading tabs. Thanks!

**Comment by phillbush** [comment]
I just added support for multiple fonts, can you test if it works for your setup?

**Comment by GideonWolfe** [comment]
What is the syntax for this? I have 

`  .font = "Hack:size=9;FontAwesome:size=10",`

But I am still getting the boxes

**Comment by phillbush** [comment]
You need to use a comma for separating the fonts.

     .font = "Hack:size=9,FontAwesome:size=10",

**Comment by GideonWolfe** [comment]
Gotcha, I tried that and `xmenu` fails to launch with the message `cannot load font`.

I ran `fc-match FontAwesome` and got `fontawesome-regular.ttf: "FontAwesome" "Regular"`

**Comment by GideonWolfe** [comment]
Ah I am extremely stupid and forgot to `git pull`. Works fantastic now.

**Comment by phillbush** [comment]
No problem!
Thanks for testing xmenu!

**Comment by GideonWolfe** [comment]
Yeah :) how can I change the lefthand padding? I am not using icons but there is still a large gap for one. I tried setting `.iconpadding` and `.horzpadding` to zero but that isn't it.

**Comment by phillbush** [comment]
Just run xmenu with the option `-i` to disable icons and remove the padding.  
For more information on the options, check the [manual](https://github.com/phillbush/xmenu/wiki).

**Comment by phillbush** [comment]
I made some changes that made xmenu smarter.

First, xmenu now knows when a menu have no icons, and remove the icon gap automatically, without the need for the `-i` option.  (The `-i` option is still necessary though for disabling icon loading, which makes xmenu loading faster.)

Second, xmenu now searches on the system for a font that contains a glyph if the fonts the user specified does not contain it or if the user did not specified fallback fonts. (However, searching the system for a font costs some time, and it may make the loading slower, so you should specify fallback fonts anyway.)

**Comment by OliverLew** [comment]
Imlib2 1.8.0 starts to support svg, but for most svg icons it seems to be rendered at 16px by 16px. Anyway it's working at least.
